apiVersion: v1
kind: Service
metadata:
  name: video-editor-server
  namespace: # TODO: your-ocp-namespace
spec:
  selector:
    app: ztube
    service: video-editor-server
  ports:
    - port: 8080
      targetPort: 8080
