apiVersion: v1
kind: Service
metadata:
  name: video-editor-server
  namespace: # TODO: your-ocp-namespace
spec:
  selector:
    app: video-editor-server
  ports:
    - port: 4001
      targetPort: 4001
