apiVersion: v1
kind: Service
metadata:
  name: video-editor-worker
  namespace: # TODO: your-ocp-namespace
  labels:
    app: video-editor-worker
spec:
  type: ClusterIP
  selector:
    app: video-editor-worker
  ports:
    - name: probe
      port: 8081
      targetPort: probe
