apiVersion: v1
kind: Service
metadata:
  name: video-editor-worker
  namespace: # TODO: your-ocp-namespace
  labels:
  app: ztube
  service: video-editor-worker
spec:
  type: ClusterIP
  selector:
    app: ztube
    service: video-editor-worker
  ports:
    - name: probe
      port: 8080
      targetPort: probe
